/**
 * Party Master Seed — 283 parties (deduplicated from 292)
 * CODE: First letter + 5-digit sequence (A00001, B00001 ... #00001 for 4C)
 *
 * REMOVED 9 branch duplicates:
 *   EVAMP TECHNOLOGIES - BANGULURU, - MUMBAI  → kept Ahmedabad main
 *   HEXA COOL PROCESS - SALE                  → kept main
 *   INOVANCE TECHNOLOGY - SURAT               → kept main
 *   KENUNIV LLP - Plant                       → kept LLP main
 *   MARUTI PLAST - ODHAV                      → kept DHAMATVAN
 *   R.H.ENTERPRISE (same as R H ENTERPRISE)   → kept one
 *   SNV AVIATION - GUJARAT, - MUMBAI          → kept DELHI
 *
 * KEPT separate (different businesses despite shared first word):
 *   MINMAX MACHINERY ≠ MINMAX PACKAGING
 *   NEELKANTH ELECTRICAL ≠ NEELKANTH ENGINEERING
 *   NEHA ENGINEERS / ENTERPRISE / INDUSTRIES
 *   MARUTI ELECTROMAC ≠ MARUTI PLAST
 *   All SHREE*, GAYATRI*, GEETA*, BHATT*, etc.
 */

const { Pool } = require('pg');
const pool = new Pool({
  host:     process.env.DB_HOST     || 'localhost',
  port:     parseInt(process.env.DB_PORT || '5432'),
  database: process.env.DB_NAME     || 'cess_tracker',
  user:     process.env.DB_USER     || 'postgres',
  password: process.env.DB_PASSWORD || 'postgres',
});

const PARTIES = [
  {code:'#00001',name:'4C CONSULTING PVT LTD',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'A00001',name:'A.M. ELECTRICALS',city:'AHMEDABAD',state:'GUJARAT',phone:'7016681291',email:'asifmansuriasifmansuri13922@gmail.com'},
  {code:'A00002',name:'AAKASH EXPLORATION SERVICES LTD',city:'AHMEDABAD',state:'GUJARAT',phone:'9157747696',email:'purchase@cess.co.in'},
  {code:'A00003',name:'AAR GEE AUTOMATION & CONTROL',city:'Patiala',state:'Punjab',phone:'8194939007',email:null},
  {code:'A00004',name:'AARVI ENGINEERING',city:'AHMEDABAD',state:'GUJARAT',phone:'9662206454',email:null},
  {code:'A00005',name:'AAYSHA ENTERPRIES',city:'AHMEDABAD',state:'GUJARAT',phone:'9898668281',email:null},
  {code:'A00006',name:'AAYUSHI IMPEX',city:'AHMEDABAD',state:'GUJARAT',phone:'9327023595',email:null},
  {code:'A00007',name:'ABBONITE PLASTICS',city:'AHMEDABAD',state:'GUJARAT',phone:'9227248009',email:null},
  {code:'A00008',name:'ACCURATE PHARMA SOLUTIONS',city:'AHMEDABAD',state:'GUJARAT',phone:'9822934908',email:null},
  {code:'A00009',name:'ACCUWEB ENTERPRISES',city:'AHMEDABAD',state:'GUJARAT',phone:'9825052676',email:null},
  {code:'A00010',name:'ADINATH EQUIPMENTS PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:'9879156589',email:null},
  {code:'A00011',name:'ALFA PUMPS (P) LIMITED',city:'AHMEDABAD',state:'GUJARAT',phone:'8141260200',email:'office@alfapumps.com'},
  {code:'A00012',name:'ALTEEM TECH PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:'9426550837',email:null},
  {code:'A00013',name:'ALUKA EXTRUSION INDUSTRIES LLP',city:'AHMEDABAD',state:'GUJARAT',phone:'7948992145',email:null},
  {code:'A00014',name:'AMBICA HONING & HYDRALICS',city:'AHMEDABAD',state:'GUJARAT',phone:'9879452578',email:null},
  {code:'A00015',name:'AMBICA VIDHYUT KARYALAY',city:'SURENDRANAGAR',state:'GUJARAT',phone:'9825381684',email:null},
  {code:'A00016',name:'AMBITION TRADELINK',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'A00017',name:'ANJALI ENTERPRISE',city:'AHMEDABAD',state:'GUJARAT',phone:'7016262825',email:null},
  {code:'A00018',name:'ANKIT TELECOM & ELECTRICALS',city:'CHHATRAL',state:'GUJARAT',phone:null,email:null},
  {code:'A00019',name:'ANTILIA TEC PACK',city:'GANDHINAGAR',state:'GUJARAT',phone:'9099013003',email:null},
  {code:'A00020',name:'ASHAPURA ENGINEERING',city:'AHMEDABAD',state:'GUJARAT',phone:'9723669758',email:null},
  {code:'A00021',name:'ATIT MANAGEMENT SERVICE PVT LTD',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'A00022',name:'ATREYO RESEARCH AND DEVELOPMENT LLP',city:'AHMEDABAD',state:'GUJARAT',phone:'9737741417',email:null},
  {code:'A00023',name:'ATUL GREEN BRICKS PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:'info.atulgreenbricks@gmail.com'},
  {code:'A00024',name:'AVI TEKSOL',city:'AHMEDABAD',state:'GUJARAT',phone:'9601274752',email:'info@aviteksol.com'},
  {code:'A00025',name:'AXIO BIOSOLUTIONS PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:'9724521761',email:'accounts@axiobio.com'},
  {code:'A00026',name:'AXIS SOLUTIONS LIMITED',city:'AHMEDABAD',state:'GUJARAT',phone:'9909905385',email:'info@axisindia.in'},
  {code:'B00001',name:'B M INDUSTRIES',city:'AHMEDABAD',state:'GUJARAT',phone:'9824095662',email:null},
  {code:'B00002',name:'BANSI POWDER COATING',city:'AHMEDABAD',state:'GUJARAT',phone:'9712608873',email:null},
  {code:'B00003',name:'BANSIDHAR POWDER COATING',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'B00004',name:'BECHRA PHARMA MACHINERY',city:'AHMEDABAD',state:'GUJARAT',phone:'8320685869',email:'sales.bpmindia@gmail.com'},
  {code:'B00005',name:'BEST HYLAM ENGINEERING',city:'AHMEDABAD',state:'GUJARAT',phone:'7405885720',email:null},
  {code:'B00006',name:'BESTOUCH INDUSTRIES',city:'CHHATRAL',state:'GUJARAT',phone:null,email:null},
  {code:'B00007',name:'BHADRA POWER PACK',city:'AHMEDABAD',state:'GUJARAT',phone:'9327010390',email:null},
  {code:'B00008',name:'BHAGWAT ENTERPRISE',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'B00009',name:'BHATT BROS TECH',city:'AHMEDABAD',state:'GUJARAT',phone:'9328084222',email:'info@bhattbrostech.com'},
  {code:'B00010',name:'BHATT MAGNETICS PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:'9426300401',email:null},
  {code:'B00011',name:'BRIGHT ENGINEERS',city:'AHMEDABAD',state:'GUJARAT',phone:'9909921694',email:'jagdish075@gmail.com'},
  {code:'B00012',name:'BRIGHT INTERNATIONAL',city:'AHMEDABAD',state:'GUJARAT',phone:'9879281986',email:null},
  {code:'B00013',name:'BRL TECH',city:'NASHIK',state:'MAHARASHTRA',phone:'9834129437',email:null},
  {code:'C00001',name:'CESRAC TECHNOLOGY PVT LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'C00002',name:'CESS DYNAMICS',city:'AHMEDABAD',state:'GUJARAT',phone:'7573080784',email:null},
  {code:'C00003',name:'CHAMUNDA INDUSTRIES',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'C00004',name:'CHROMITE ENGINEERING PVT LTD',city:'AHMEDABAD',state:'GUJARAT',phone:'9909285755',email:null},
  {code:'C00005',name:'CIP MACHINERIES PVT. LTD',city:'AHMEDABAD',state:'GUJARAT',phone:'9909981395',email:'sales@cipmach.com'},
  {code:'C00006',name:'COMPLETE FILTRATION AND UTILITY',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'C00007',name:'CONVELINE SYSTEMS PVT. LTD',city:'AHMEDABAD',state:'GUJARAT',phone:'7486012740',email:null},
  {code:'C00008',name:'CRESTA INSTRUMENTS',city:'MUMBAI',state:'MAHARASHTRA',phone:null,email:null},
  {code:'D00001',name:'DADA INDUSTRIES',city:'AHMEDABAD',state:'GUJARAT',phone:'9512023237',email:null},
  {code:'D00002',name:'DAXTEL TECHNOLOGY',city:'AHMEDABAD',state:'GUJARAT',phone:'9328341242',email:null},
  {code:'D00003',name:'DELTA ELECTRONICS INDIA PVT LTD',city:'Gurgaon',state:'Haryana',phone:null,email:null},
  {code:'D00004',name:'DEV TRADING CO.',city:'AHMEDABAD',state:'GUJARAT',phone:'9909944565',email:'sales@devpackers.com'},
  {code:'D00005',name:'DFURN MODULAR SYSTEMS PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:'minesh@dfurn.in'},
  {code:'D00006',name:'DHRUVESH INDUSTRIES',city:'AHMEDABAD',state:'GUJARAT',phone:'9173376111',email:null},
  {code:'D00007',name:'DHRUVI OFFSET',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'D00008',name:'DHRUVI TEXTILE ENGINEERING PVT. LTD.',city:'SURAT',state:'GUJARAT',phone:null,email:null},
  {code:'D00009',name:'DHWANI ENTERPRISE',city:'RAJKOT',state:'GUJARAT',phone:'9712503434',email:null},
  {code:'D00010',name:'DIVYA MANPOWER MANAGMENT SERVICE',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'D00011',name:'DNS AGRO FOODS PVT. LTD.',city:'HYDERABAD',state:'TELANGANA',phone:'9909172899',email:null},
  {code:'D00012',name:'DTM TECHNOLOGIES',city:'AHMEDABAD',state:'GUJARAT',phone:'6351597202',email:null},
  {code:'D00013',name:'DUDHAT INFRA PRODUCTS LIMITED',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'E00001',name:'E-LOGIC ELECTROMATION',city:'AHMEDABAD',state:'GUJARAT',phone:'9727689891',email:null},
  {code:'E00002',name:'ELECON PERIPHERALS LIMITED',city:'ANAND',state:'GUJARAT',phone:'9712946239',email:'slvasu@epl.elecon.com'},
  {code:'E00003',name:'ELECSYS POWER CONTROL',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:'hemant.prajapati@elecsys.in'},
  {code:'E00004',name:'EQUISCALE TECHNOLOGIES',city:'VAPI',state:'GUJARAT',phone:null,email:null},
  {code:'E00005',name:'EVA AUTOMATION',city:'AHMEDABAD',state:'GUJARAT',phone:'9313515135',email:'rahul.sevak@yahoo.com'},
  {code:'E00006',name:'EVAMP TECHNOLOGIES PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'E00007',name:'EVERON GEARS PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'E00008',name:'EXTRUMAC ENGINEERS',city:'AHMEDABAD',state:'GUJARAT',phone:'9426525226',email:null},
  {code:'F00001',name:'FAS MECHATRONICS',city:'VADODARA',state:'GUJARAT',phone:'9537903239',email:null},
  {code:'F00002',name:'FASHION ART PRINTERS',city:'THANE',state:'MAHARASHTRA',phone:'9821656713',email:'fashionartprinters78@gmail.com'},
  {code:'F00003',name:'FERROSLIT MACHINERY PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'F00004',name:'FINETECH INDUSTRIES',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'F00005',name:'FORTUNE PHARMATECH',city:'AHMEDABAD',state:'GUJARAT',phone:'9727177701',email:null},
  {code:'F00006',name:'FRY AND BAKE TECHNOLOGIES PVT LTD',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'F00007',name:'FUSION TECH SOLUTIONS',city:'AHMEDABAD',state:'GUJARAT',phone:'9099088885',email:null},
  {code:'F00008',name:'FUTURISTIC CLIMATE CONTROLS PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:'7201000729',email:'sales@futuristicclimatecontrols.in'},
  {code:'F00009',name:'FUTURISTIC TECHNOLOGIES',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'G00001',name:'GAJROLL TECHNOLOGY PVT LTD',city:'AHMEDABAD',state:'GUJARAT',phone:'9687606380',email:'sales@gajroll.com'},
  {code:'G00002',name:'GANESH PAPAD PRODUCTS',city:'ANAND',state:'GUJARAT',phone:null,email:null},
  {code:'G00003',name:'GAYATRI RUB TECH',city:'AHMEDABAD',state:'GUJARAT',phone:'9510164193',email:null},
  {code:'G00004',name:'GAYATRI TEXTILE MACHINES',city:'AHMEDABAD',state:'GUJARAT',phone:'07922775403',email:'gayatrirrp@gmail.com'},
  {code:'G00005',name:'GEE TEX MILLS',city:'AHMEDABAD',state:'GUJARAT',phone:'9879585461',email:null},
  {code:'G00006',name:'GEETA INFRASTRUCTURES',city:'AHMEDABAD',state:'GUJARAT',phone:'07947422803',email:null},
  {code:'G00007',name:'GEETA METALS AND SUPPLY CO.',city:'AHMEDABAD',state:'GUJARAT',phone:'9825607566',email:null},
  {code:'G00008',name:'GPZ ENGINEERS PVT. LTD.',city:'PUNE',state:'MAHARASHTRA',phone:'8007218944',email:'gpzepl@gmail.com'},
  {code:'G00009',name:'GRINDOMAC INDUSTRIES',city:'AHMEDABAD',state:'GUJARAT',phone:'9601449500',email:null},
  {code:'G00010',name:'GURUKRUPA TRADING CO.',city:'AHMEDABAD',state:'GUJARAT',phone:'9825963443',email:null},
  {code:'H00001',name:'H HARVI ENGINEERING',city:'MEHSANA',state:'GUJARAT',phone:'9909978964',email:'piyush@hharvi.com'},
  {code:'H00002',name:'H K SOFTWARE',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'H00003',name:'HARE PLASTIC',city:'AHMEDABAD',state:'GUJARAT',phone:'7041401154',email:null},
  {code:'H00004',name:'HARIKRUSHNA AUTOMATION',city:'AHMEDABAD',state:'GUJARAT',phone:'7984181841',email:'saleshkautomation@gmail.com'},
  {code:'H00005',name:'HARVI ELECTRICALS',city:'Valsad',state:'Gujarat',phone:'9157625464',email:'sales@harvielectricals.com'},
  {code:'H00006',name:'HEXA COOL PROCESS PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:'9687524629',email:null},
  {code:'H00007',name:'HEXAGON TECHNOLOGY',city:'AHMEDABAD',state:'GUJARAT',phone:'9574340160',email:null},
  {code:'H00008',name:'HIECON TECHNOLOGIES PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'H00009',name:'HOKABAJ GRAPHICS',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'I00001',name:'IGE+XAC INDIA PVT LTD',city:'BENGALURU',state:'KARNATAKA',phone:null,email:null},
  {code:'I00002',name:'INDIAN SPERMTECH',city:'AHMEDABAD',state:'GUJARAT',phone:'9426059805',email:null},
  {code:'I00003',name:'INDUS CRYOBANK',city:'SURAT',state:'GUJARAT',phone:'9726019991',email:null},
  {code:'I00004',name:'INOVANCE TECHNOLOGY PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:'gaurang.bhojak@inovance.ind.in'},
  {code:'I00005',name:'INSH PRINTS',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'I00006',name:'INTECH GLASS',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'I00007',name:'IRIS INDUSTRIES',city:'AHMEDABAD',state:'GUJARAT',phone:'7201905236',email:null},
  {code:'I00008',name:'ISOQAR INDIA PVT LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'I00009',name:'IVRCL LIMITED',city:'Kutch',state:'Gujarat',phone:'9909977250',email:null},
  {code:'J00001',name:'J. M. TEXTILE',city:'AHMEDABAD',state:'GUJARAT',phone:'9825586800',email:null},
  {code:'J00002',name:'JALDI SOLUTIONS',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'J00003',name:'JAY MAHAVEER STEELS',city:'AHMEDABAD',state:'GUJARAT',phone:'8128263991',email:'jmsteels4775@gmail.com'},
  {code:'J00004',name:'JAY SANTOSHI ENTERPRISE',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'J00005',name:'JAYDEEP POLYMERS',city:'AHMEDABAD',state:'GUJARAT',phone:'8200722917',email:null},
  {code:'J00006',name:'JINENDRA SALES',city:'AHMEDABAD',state:'GUJARAT',phone:'9173398855',email:null},
  {code:'J00007',name:'JSK INDUSTRIES',city:'AHMEDABAD',state:'GUJARAT',phone:'9979703614',email:null},
  {code:'K00001',name:'K.P.AUTOMATION & CONTROL',city:'AHMEDABAD',state:'GUJARAT',phone:'9687177867',email:null},
  {code:'K00002',name:'KALASH CORPORATION',city:'AHMEDABAD',state:'GUJARAT',phone:'8238031604',email:null},
  {code:'K00003',name:'KENUNIV LLP',city:'AHMEDABAD',state:'GUJARAT',phone:'8849075238',email:null},
  {code:'K00004',name:'KESHAR ENGINEERING WORKS',city:'KADI',state:'GUJARAT',phone:null,email:null},
  {code:'K00005',name:'KHODIYAR INDUSTRIES',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'K00006',name:'KNACK FLEXIPACK LLP',city:'MEHSANA',state:'GUJARAT',phone:null,email:null},
  {code:'K00007',name:'KOHINOOR ENTERPRISE',city:'AHMEDABAD',state:'GUJARAT',phone:'9727704942',email:'kohinoorent4942@gmail.com'},
  {code:'L00001',name:'L.J. LABLES',city:'AHMEDABAD',state:'GUJARAT',phone:'8320875246',email:null},
  {code:'L00002',name:'LABBDHI PAPER TUBES PVT LTD',city:'KHEDA',state:'GUJARAT',phone:'9825850230',email:null},
  {code:'L00003',name:'LAXMI EN-FAB PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'L00004',name:'LAXMI ENGINEERING EQUIPMENT',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'L00005',name:'LUOVA TECHNOLGIES PVT LTD',city:'VADODARA',state:'GUJARAT',phone:'02652985660',email:null},
  {code:'M00001',name:'M H ENGINEERING',city:'MEHSANA',state:'GUJARAT',phone:'9824544198',email:'starharoon143@gmail.com'},
  {code:'M00002',name:'M P BLOWERS PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:'07940063778',email:'info@airkingblower.com'},
  {code:'M00003',name:'M. D. ENGINEERING WORKS',city:'AHMEDABAD',state:'GUJARAT',phone:'9898142645',email:null},
  {code:'M00004',name:'M.K. ASSOCIATES',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'M00005',name:'MAA CHAMUNDA PHARMA EQUIPMENTS',city:'AHMEDABAD',state:'GUJARAT',phone:'9490931466',email:null},
  {code:'M00006',name:'MAAN ELECTRO CONTROLS',city:'AHMEDABAD',state:'GUJARAT',phone:'9313101834',email:'info@maanelectrocontrols.com'},
  {code:'M00007',name:'MAHADEV TRADING',city:'AHMEDABAD',state:'GUJARAT',phone:'9065874599',email:'mahadevtrading1310@gmail.com'},
  {code:'M00008',name:'MAHALAXMI ENTERPRISE',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:'me.machcenter@gmail.com'},
  {code:'M00009',name:'MAHASHAKTI RMC',city:'AHMEDABAD',state:'GUJARAT',phone:'9426665149',email:null},
  {code:'M00010',name:'MAHESH ENTERPRISE',city:'AHMEDABAD',state:'GUJARAT',phone:'6352460676',email:null},
  {code:'M00011',name:'MAHESHBHAI TRIBHOVANBHAI PRAJAPATI',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'M00012',name:'MAHI ENTERPRISE',city:'AHMEDABAD',state:'GUJARAT',phone:'9974912301',email:null},
  {code:'M00013',name:'MAMATA MACHINERY LIMITED',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'M00014',name:'MANN SIGN',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'M00015',name:'MARK ENTERPRISE',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'M00016',name:'MARUT AIR SYSTEMS PVT LTD',city:'MEHSANA',state:'GUJARAT',phone:'9227857018',email:null},
  {code:'M00017',name:'MARUTI ELECTROMAC',city:'AHMEDABAD',state:'GUJARAT',phone:'9825036550',email:'marutielectromac95@gmail.com'},
  {code:'M00018',name:'MARUTI PLAST',city:'AHMEDABAD',state:'GUJARAT',phone:'9925096562',email:null},
  {code:'M00019',name:'MASCOT PUMP LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:'8672023661',email:null},
  {code:'M00020',name:'MATRUCHHAYA CORPORATION',city:'VADODARA',state:'GUJARAT',phone:'9426782103',email:null},
  {code:'M00021',name:'MAXXEN INTERNATIONAL',city:'AHMEDABAD',state:'GUJARAT',phone:'8485942681',email:null},
  {code:'M00022',name:'MECHENO MACHINERY',city:'AHMEDABAD',state:'GUJARAT',phone:'8849816058',email:null},
  {code:'M00023',name:'MEDICLAVE INDUSTRIES PVT LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:'9687116314',email:null},
  {code:'M00024',name:'MEHTA EXPAI TECHNOLOGIES PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:'7229045312',email:null},
  {code:'M00025',name:'MELT SEAL',city:'GANDHINAGAR',state:'GUJARAT',phone:'6351302981',email:null},
  {code:'M00026',name:'MGM EXPORT',city:'RAJKOT',state:'GUJARAT',phone:'02823222103',email:null},
  {code:'M00027',name:'MIFA SYSTEMS',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'M00028',name:'MINDRA EV PVT LTD',city:'AHMEDABAD',state:'GUJARAT',phone:'6352165681',email:'purchase@mindraev.com'},
  {code:'M00029',name:'MINMAX MACHINERY PRIVATE LIMITED',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'M00030',name:'MINMAX PACKAGING',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'M00031',name:'MIRACLE AUTOMATION',city:'AHMEDABAD',state:'GUJARAT',phone:'9726493931',email:null},
  {code:'M00032',name:'MODERN INDUSTRIES',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'M00033',name:'MOTOSPIN INDIA',city:'AHMEDABAD',state:'GUJARAT',phone:'9913983694',email:null},
  {code:'N00001',name:'N-TEX MACHINARY PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'N00002',name:'N.G.U. FOODS AND BEVERAGES LLP',city:'AHMEDABAD',state:'GUJARAT',phone:'9925021500',email:null},
  {code:'N00003',name:'NAKSH TECHNOLOGY SOLUTION LLP',city:'AHMEDABAD',state:'GUJARAT',phone:'9974189899',email:null},
  {code:'N00004',name:'NATIONAL PRODUCTIVITY COUNCIL',city:'Delhi',state:'Delhi',phone:null,email:'npcinfo@npcindia.gov.in'},
  {code:'N00005',name:'NEEC ELECTROTECH PVT LTD',city:'VADODARA',state:'GUJARAT',phone:'6355912423',email:null},
  {code:'N00006',name:'NEELKANTH ELECTRICAL',city:'AHMEDABAD',state:'GUJARAT',phone:'9725098756',email:null},
  {code:'N00007',name:'NEELKANTH ENGINEERING',city:'AHMEDABAD',state:'GUJARAT',phone:'9426758314',email:null},
  {code:'N00008',name:'NEHA ENGINEERS',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'N00009',name:'NEHA ENTERPRISE',city:'AHMEDABAD',state:'GUJARAT',phone:'9825079081',email:null},
  {code:'N00010',name:'NEHA INDUSTRIES',city:'AHMEDABAD',state:'GUJARAT',phone:'9825079081',email:null},
  {code:'N00011',name:'NEO INDUSTRIES',city:'AHMEDABAD',state:'GUJARAT',phone:'9825616414',email:null},
  {code:'N00012',name:'NEOTECH MACHINERY',city:'AHMEDABAD',state:'GUJARAT',phone:'9825360319',email:null},
  {code:'N00013',name:'NEPTUNE POLYMERS PVT.LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'N00014',name:'NIRAVARE POLYMERS',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'N00015',name:'NISHARG ENGINEERING WORKS',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'N00016',name:'NISUKA INDUSTRIES PVT LTD',city:'AHMEDABAD',state:'GUJARAT',phone:'7940051186',email:null},
  {code:'N00017',name:'NUVISTA AUTOMATION',city:'AHMEDABAD',state:'GUJARAT',phone:'9409963937',email:'nuvistaautomation@gmail.com'},
  {code:'O00001',name:'OMEGA CONTROLS',city:'AHMEDABAD',state:'GUJARAT',phone:'7984266567',email:'omegacontrols1@outlook.com'},
  {code:'P00001',name:'P S PHARMATECH',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'P00002',name:'PADME BOTANICS PVT LTD',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'P00003',name:'PANCHAL CHIRAG',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'P00004',name:'PANCHAL MAYANK MANUBHAI',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'P00005',name:'PANCHAL VISNUBHAI NATHABHAI',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'P00006',name:'PARADISE INDUSTRY MACHINERY PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:'9313841637',email:null},
  {code:'P00007',name:'PARINAY',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'P00008',name:'PITSON TRANSMISSION TECHNOLOGIES',city:'SURENDRANAGAR',state:'GUJARAT',phone:'8141404072',email:null},
  {code:'P00009',name:'POWER CONTROLS',city:'VADODARA',state:'GUJARAT',phone:'9825045529',email:null},
  {code:'P00010',name:'POWER DRIVE BEARINGS PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'P00011',name:'PRAJAPATI SANJAY PREHLAD BHAI',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'P00012',name:'PRAKASH ENGINEERING',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'P00013',name:'PRAKRUTI INDUSTRIES',city:'VADODARA',state:'GUJARAT',phone:null,email:null},
  {code:'P00014',name:'PRAMA HIKVISION INDIA PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:'7573915728',email:null},
  {code:'P00015',name:'PRAYAS ENGINEERING LIMITED',city:'VADODARA',state:'GUJARAT',phone:null,email:null},
  {code:'P00016',name:'PREKSHA INTERIORS PVT LTD',city:'AHMEDABAD',state:'GUJARAT',phone:'9727982828',email:null},
  {code:'P00017',name:'PRISM TEST AND MEASURE PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:'9099062852',email:null},
  {code:'P00018',name:'PURPI COMFERTORS PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:'8238514772',email:null},
  {code:'Q00001',name:'QASCO MACHINERY',city:'AHMEDABAD',state:'GUJARAT',phone:'7016511476',email:null},
  {code:'Q00002',name:'QUALITY MACHINE PRODUCTS',city:'RAJKOT',state:'GUJARAT',phone:null,email:null},
  {code:'R00001',name:'R H ENTERPRISE',city:'KHEDA',state:'GUJARAT',phone:'9408218427',email:'info@rhentp.in'},
  {code:'R00002',name:'R R INDUSTRIES',city:'KHEDA',state:'GUJARAT',phone:'9662223963',email:'info@rrinduatries.biz'},
  {code:'R00003',name:'R.D. DHAMECHA & CO',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'R00004',name:'R.D.ASSOCIATES',city:'AHMEDABAD',state:'GUJARAT',phone:'9824520049',email:null},
  {code:'R00005',name:'RADHA MADHAV ENGINEERING SOLUTION',city:'AHMEDABAD',state:'GUJARAT',phone:'6354603161',email:'madhavradha332@gmail.com'},
  {code:'R00006',name:'RAJA STEELS',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'R00007',name:'RAJHANS PLASTICS MACHINARY PVT LTD',city:'AHMEDABAD',state:'GUJARAT',phone:'07925830003',email:null},
  {code:'R00008',name:'RAJU RAJA RAM (JAY AMBE GYPSUM)',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'R00009',name:'RAMESHWAR STEEL FAB',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'R00010',name:'RANADE S SR SYSTEMS PVT. LTD.',city:'MUMBAI',state:'MAHARASHTRA',phone:null,email:null},
  {code:'R00011',name:'RAY MACHINE TECH (INDIA) LLP',city:'AHMEDABAD',state:'GUJARAT',phone:'9824742154',email:null},
  {code:'R00012',name:'RD TENDER JEETO LLP',city:'AHMEDABAD',state:'GUJARAT',phone:'9898100235',email:'sales@tenderjeeto.com'},
  {code:'R00013',name:'REBOOT AUTOMATION',city:'Valsad',state:'Gujarat',phone:'9979569202',email:'rebootautomation@gmail.com'},
  {code:'R00014',name:'REENA PROCESSORS PRIVATE LIMITED',city:'SURAT',state:'GUJARAT',phone:null,email:null},
  {code:'R00015',name:'RELIANT FOOD PROCESSING',city:'Bokaro',state:'Jharkhand',phone:'8987495773',email:null},
  {code:'R00016',name:'RIDDHI CONTROL SYSTEM',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'R00017',name:'ROHIT INDUSTRIES',city:'SURENDRANAGAR',state:'GUJARAT',phone:'9898320537',email:null},
  {code:'R00018',name:'ROYAL SUNDARAM GENERAL INSURANCE',city:'SURAT',state:'GUJARAT',phone:null,email:null},
  {code:'R00019',name:'ROYAL TEXTILE',city:'RAJKOT',state:'GUJARAT',phone:'9909039922',email:null},
  {code:'R00020',name:'RUBEENA SCREEN PRINTS',city:'AHMEDABAD',state:'GUJARAT',phone:'9227215088',email:null},
  {code:'R00021',name:'RUSHIL ENTERPRISE',city:'AHMEDABAD',state:'GUJARAT',phone:'6355575552',email:null},
  {code:'S00001',name:'S J MACHINERY',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'S00002',name:'S S SODA MACHINE',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'S00003',name:'S.J.ENGINEERS WORKS',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'S00004',name:'SADGURU POLYPACK',city:'RAJKOT',state:'GUJARAT',phone:'9428891570',email:null},
  {code:'S00005',name:'SADGURU STRAPS',city:'RAJKOT',state:'GUJARAT',phone:'7859800400',email:null},
  {code:'S00006',name:'SADHI MACHINERY PLASTIC PRODUCT',city:'AHMEDABAD',state:'GUJARAT',phone:'823844889',email:null},
  {code:'S00007',name:'SAFEX FIRE SERVICES LIMITED',city:'MUMBAI',state:'MAHARASHTRA',phone:'9270652115',email:null},
  {code:'S00008',name:'SAHJANAND SALES CORPORATION',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'S00009',name:'SAI SYSTEM AND CONTROL',city:'AHMEDABAD',state:'GUJARAT',phone:'07948973773',email:null},
  {code:'S00010',name:'SAMIRIKA INDUSTRIES PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:'9601711600',email:null},
  {code:'S00011',name:'SANOLET LIFECARE PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:'7227028295',email:null},
  {code:'S00012',name:'SANWALIYA INDUSTRIES',city:'Alwar',state:'Rajasthan',phone:'9327008652',email:null},
  {code:'S00013',name:'SATYAM MICRO SYSTEM',city:'AHMEDABAD',state:'GUJARAT',phone:'9824093509',email:null},
  {code:'S00014',name:'SHIV CARE CHEMICALS',city:'AHMEDABAD',state:'GUJARAT',phone:'9909705806',email:'shivcarechemicals@gmail.com'},
  {code:'S00015',name:'SHOCKWAVE SOLUTION PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:'9898626605',email:null},
  {code:'S00016',name:'SHREE ELECTROLINK',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'S00017',name:'SHREE GANESH ENTERPRISE',city:'AHMEDABAD',state:'GUJARAT',phone:'9925399022',email:null},
  {code:'S00018',name:'SHREE HARIKRISHNA PHARMACEUTICALS PVT LTD',city:'AHMEDABAD',state:'GUJARAT',phone:'8200665486',email:null},
  {code:'S00019',name:'SHREE LAXMI ENGINEERS',city:'MUMBAI',state:'MAHARASHTRA',phone:'9820944894',email:null},
  {code:'S00020',name:'SHREE MARUTI ENTERPRISE',city:'VADODARA',state:'GUJARAT',phone:'8200243892',email:null},
  {code:'S00021',name:'SHREE RADHEKRISHNA EXTRUTECH PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'S00022',name:'SHREE SAINATH INDUSTRIES',city:'AHMEDABAD',state:'GUJARAT',phone:'7567007990',email:null},
  {code:'S00023',name:'SHREEJI INDUSTRIES',city:'AHMEDABAD',state:'GUJARAT',phone:'9879609541',email:null},
  {code:'S00024',name:'SHRI ALKA INDUSTRIES',city:'MEHSANA',state:'GUJARAT',phone:'9909031836',email:null},
  {code:'S00025',name:'SHRI RAM ENTERPRISE',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:'shriramenterprise853@gmail.com'},
  {code:'S00026',name:'SIDDHIVINAYAK POWDER COATS',city:'AHMEDABAD',state:'GUJARAT',phone:'9724168193',email:null},
  {code:'S00027',name:'SIGMA CONTROLS',city:'AHMEDABAD',state:'GUJARAT',phone:'9558098526',email:null},
  {code:'S00028',name:'SMITA AUTOMATION & CONTROLS',city:'Pune',state:'Maharashtra',phone:null,email:null},
  {code:'S00029',name:'SNV AVIATION PRIVATE LIMITED',city:'Delhi',state:'Delhi',phone:null,email:null},
  {code:'S00030',name:'SOHAN ENTERPRISE',city:'AHMEDABAD',state:'GUJARAT',phone:'9824054142',email:'sohanent@ymail.com'},
  {code:'S00031',name:'SONU CORPORATION',city:'AHMEDABAD',state:'GUJARAT',phone:'9925004511',email:null},
  {code:'S00032',name:'SOUL ELECTRIC PVT. LTD.',city:'VADODARA',state:'GUJARAT',phone:null,email:'haresh@soulelectric.in'},
  {code:'S00033',name:'SR INDUS ELECTRO SYS PRIVATE LIMITED',city:'BENGALURU',state:'KARNATAKA',phone:null,email:null},
  {code:'S00034',name:'SSC CONTROL PVT. LTD.',city:'VADODARA',state:'GUJARAT',phone:'9033031789',email:null},
  {code:'S00035',name:'STAR AUTOMATION SOLUTION',city:'AHMEDABAD',state:'GUJARAT',phone:'6395052681',email:null},
  {code:'S00036',name:'SU PARSHWA TEXPRINT LLP',city:'AHMEDABAD',state:'GUJARAT',phone:'9998028199',email:'suparshwatex@gmail.com'},
  {code:'S00037',name:'SUMIT EMPOWERING AUTOMATION PVT.LTD',city:'AHMEDABAD',state:'GUJARAT',phone:'9427988347',email:null},
  {code:'S00038',name:'SUN ACRYLAM PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:'8530028504',email:null},
  {code:'T00001',name:'TACHYONS LIFESCIENCE PVT. LTD.',city:'HIMATNAGAR',state:'GUJARAT',phone:'9979733901',email:null},
  {code:'T00002',name:'TANISHQ INDUSTRIES',city:'AHMEDABAD',state:'GUJARAT',phone:'9327008652',email:null},
  {code:'T00003',name:'TAPEPACK',city:'AHMEDABAD',state:'GUJARAT',phone:'9023234041',email:null},
  {code:'T00004',name:'TASKAR ENGINEERING',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'T00005',name:'TATVA ENTERPRISE',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'T00006',name:'TECHNO ENGINEERING HUB',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'T00007',name:'TEXEL INDUSTRIES LTD.',city:'KHEDA',state:'GUJARAT',phone:'8980028650',email:'purchase@geotexelin.com'},
  {code:'T00008',name:'TEXWORLD FASHIONS PVT LTD',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'T00009',name:'THE OLD SLATE',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'T00010',name:'TITLE DISPLAY SYSTEM PVT LTD',city:'KADI',state:'GUJARAT',phone:null,email:null},
  {code:'T00011',name:'TRIGGER AUTOMATION',city:'GANDHINAGAR',state:'GUJARAT',phone:'9726687716',email:'triggersautomation@gmail.com'},
  {code:'U00001',name:'URVANSH ENTERPRISE',city:'AHMEDABAD',state:'GUJARAT',phone:'9586001468',email:null},
  {code:'V00001',name:'VARDHMAN FURNITURE',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'V00002',name:'VARSHA CREATION',city:'RAJKOT',state:'GUJARAT',phone:'8511966644',email:null},
  {code:'V00003',name:'VIJAYKUMAR R. OZA',city:'AHMEDABAD',state:'GUJARAT',phone:'9924202117',email:null},
  {code:'V00004',name:'VIKAS SALES CORPORATION',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'V00005',name:'VISVES ADVANCE ENGINEERING PVT LTD',city:'AHMEDABAD',state:'GUJARAT',phone:'8866863982',email:null},
  {code:'V00006',name:'VLAC MULTIPLE PRODUCTS',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'V00007',name:'VS PHARMA MACHINES',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'W00001',name:'WEARE ENTERPRISE',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'W00002',name:'WELLTECH ELECTRONICS',city:'AHMEDABAD',state:'GUJARAT',phone:'9925899282',email:null},
  {code:'W00003',name:'WEMICON AUTOMATION SYSTEMS LLP',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'W00004',name:'WINDSOR AUTOMATION',city:'AHMEDABAD',state:'GUJARAT',phone:'9722367009',email:'info@windsorautomation.com'},
  {code:'X00001',name:'XEXAGON HI-TECH PVT. LTD.',city:'AHMEDABAD',state:'GUJARAT',phone:'7778948838',email:null},
  {code:'X00002',name:'XLRATE TECHNOLOGIES PVT LTD',city:'Mumbai',state:'Maharashtra',phone:null,email:null},
  {code:'Y00001',name:'YADAV ANAND R. (LABOUR)',city:'MUMBAI',state:'MAHARASHTRA',phone:null,email:null},
  {code:'Y00002',name:'YAMIN PRINT',city:'AHMEDABAD',state:'GUJARAT',phone:null,email:null},
  {code:'Y00003',name:'YOGI SALES PVT LTD',city:'AHMEDABAD',state:'GUJARAT',phone:'9825010764',email:null},
];

async function seed() {
  console.log(`\nSeeding ${PARTIES.length} parties (283 after dedup)...\n`);
  await pool.query('TRUNCATE party_master RESTART IDENTITY CASCADE');
  let ok = 0, fail = 0;
  for (const p of PARTIES) {
    try {
      await pool.query(
        `INSERT INTO party_master (code,name,city,state,phone,email) VALUES ($1,$2,$3,$4,$5,$6)`,
        [p.code, p.name, p.city, p.state, p.phone||null, p.email?p.email.toLowerCase():null]
      );
      process.stdout.write('✅'); ok++;
    } catch(e) {
      console.log(`\n❌ ${p.code} ${p.name}: ${e.message}`); fail++;
    }
  }
  const {rows} = await pool.query(`SELECT COUNT(*) total, COUNT(phone) with_phone, COUNT(email) with_email FROM party_master`);
  console.log(`\n\n${'═'.repeat(40)}`);
  console.log('  PARTY MASTER SEEDING COMPLETE');
  console.log('═'.repeat(40));
  console.log(`  Inserted : ${ok}   Failed: ${fail}`);
  console.log(`  With phone: ${rows[0].with_phone}`);
  console.log(`  With email: ${rows[0].with_email}`);
  console.log('═'.repeat(40)+'\n');
  await pool.end();
}

seed().catch(e=>{console.error('Fatal:',e.message);process.exit(1);});